select * from customer;
 -- total revenue generated by male vs female 
 select gender, sum(purchase_amount)as revenue from customer
 group by gender;

 -- which customer used discounts but still spent more than avg purchase amount
 select * from customer
 where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount)from customer);

 -- which are the top 5 product with highest average review rating?
 select item_purchased, round(avg(review_rating::numeric),2) from customer
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;

-- compare the avg purchase aount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2) from customer
group by shipping_type
having shipping_type in ('Standard','Express');

-- do subscribed customers spend more? compare avg spend and total revenue
-- between subscribers and no-subscribers
select subscription_status,count(subscription_status), round(avg(purchase_amount),2) as avg_amt ,round(sum(purchase_amount),2) as total_revenue from customer
group by subscription_status;

-- which 5 products have the highest percentage of purchases with discount
select item_purchased,
100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*)||'%' as disccount_rate from customer
group by item_purchased
order by disccount_rate desc
limit 5;

-- segment customers into new, returning, and loyal based on their total number 
-- of previous purchases, and show the count of each segment 
with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases < 7 then 'new' 
     when previous_purchases < 25 then 'returning'
	 else 'loyal'
	 end as segment 
from customer
)
select segment, count(*) from customer_type
group by segment;

-- what are the top 3 most purchased product within each category
with item_count as (
select item_purchased,category, count(customer_id) as item_no,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by item_purchased,category
)
select item_rank, item_purchased, category, item_no from item_count
where item_rank<= 3;

-- customers who are repeat buyers (more than 5 perious purchases) also likely to subscribe
select subscription_status,count(customer_id) previous_purchases from customer
where previous_purchases > 5
group by subscription_status;

-- what is revenue contribution of each age group 
select age_group, sum(purchase_amount) as revenue_by_age from customer
group by age_group
order by sum(purchase_amount) desc ;



 